/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GarageServicesRouteImport } from './routes/garage-services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VehicleRecovery247RouteImport } from './routes/vehicle-recovery-24-7'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageServicesRoute = GarageServicesRouteImport.update({
  id: '/garage-services',
  path: '/garage-services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleRecovery247Route = VehicleRecovery247RouteImport.update({
  id: '/vehicle-recovery-24-7',
  path: '/vehicle-recovery-24-7',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/garage-services': typeof GarageServicesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/vehicle-recovery-24-7': typeof VehicleRecovery247Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/garage-services': typeof GarageServicesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/vehicle-recovery-24-7': typeof VehicleRecovery247Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/garage-services': typeof GarageServicesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/vehicle-recovery-24-7': typeof VehicleRecovery247Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact'
    | '/garage-services'
    | '/privacy'
    | '/terms'
    | '/vehicle-recovery-24-7'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact'
    | '/garage-services'
    | '/privacy'
    | '/terms'
    | '/vehicle-recovery-24-7'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact'
    | '/garage-services'
    | '/privacy'
    | '/terms'
    | '/vehicle-recovery-24-7'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactRoute: typeof ContactRoute
  GarageServicesRoute: typeof GarageServicesRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  VehicleRecovery247Route: typeof VehicleRecovery247Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage-services': {
      id: '/garage-services'
      path: '/garage-services'
      fullPath: '/garage-services'
      preLoaderRoute: typeof GarageServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-recovery-24-7': {
      id: '/vehicle-recovery-24-7'
      path: '/vehicle-recovery-24-7'
      fullPath: '/vehicle-recovery-24-7'
      preLoaderRoute: typeof VehicleRecovery247RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactRoute: ContactRoute,
  GarageServicesRoute: GarageServicesRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  VehicleRecovery247Route: VehicleRecovery247Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
